# --------------------------------------------------------------------
# ai
# --------------------------------------------------------------------
server {
    listen 443 ssl;
    server_name ai.iskarion.ddns.net;
    ssl_certificate /etc/letsencrypt/live/ai.iskarion.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ai.iskarion.ddns.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    #location /ws/ {
    #    proxy_pass http://localhost:8080; # Ajusta el puerto de tu app
    #    proxy_http_version 1.1;
    #    proxy_set_header Upgrade $http_upgrade;
    #    proxy_set_header Connection "Upgrade";
    #    proxy_set_header Host $host;    
    #}

    location / {
        proxy_pass http://ai-service:8000;

        # Soporte WebSocket vital para SocketIO
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host ai.iskarion.ddns.net;
        proxy_redirect off;

        # Evita cortes en streams largos de IA
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
