# Tetris
    server {
        listen 443 ssl;
        server_name tetris.iskarion.ddns.net;

        ssl_certificate /etc/letsencrypt/live/tetris.iskarion.ddns.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tetris.iskarion.ddns.net/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        include error.conf;

        location / {
            proxy_pass http://tetris-service:80;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host tetris.iskarion.ddns.net;
            proxy_redirect off;
        }
    }
