# TrickyNoid
    # Frontend
    server {
        listen 443 ssl;
        server_name trickynoid.iskarion.ddns.net;

        root /var/www/html;
        index index.php index.html;

        ssl_certificate /etc/letsencrypt/live/trickynoid.iskarion.ddns.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/trickynoid.iskarion.ddns.net/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Procesar archivos PHP mediante el protocolo FastCGI
        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            # Conexión al contenedor PHP-FPM
            fastcgi_pass trickynoid-front-service:9000;
        }
        # Enrutamiento para solicitudes principales
        location / {
            # Enviamos la petición hacia el index.php para que lo procese el bloque de arriba
            try_files $uri $uri/ /index.php?$query_string;
        }
    }

    # Backend
    server {
        listen 443 ssl;
        server_name api.trickynoid.iskarion.ddns.net;

        ssl_certificate /etc/letsencrypt/live/api.trickynoid.iskarion.ddns.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.trickynoid.iskarion.ddns.net/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Archivos estáticos de Django
        location /static/ {
            alias /static/trickynoid/;
        }

        # Archivos multimedia de Django
        location /media/ {
            alias /media/trickynoid/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Enrutamiento para solicitudes principales
        location / {
            proxy_pass http://trickynoid-back-service:8000/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host api.trickynoid.iskarion.ddns.net;
            proxy_redirect off;
        }
    }
