# Warhammer
    server {
        listen 443 ssl;
        server_name warhammer.iskarion.ddns.net;

        ssl_certificate /etc/letsencrypt/live/warhammer.iskarion.ddns.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/warhammer.iskarion.ddns.net/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        include error.conf;

        # Archivos estáticos de Django
        location /static/ {
            alias /static/warhammer/;
        }

        # Archivos multimedia de Django
        location /media/ {
            alias /media/warhammer/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Proxy inverso para solicitudes dinámicas conectando con tu upstream
        location / {
            proxy_pass http://warhammer-service:8000;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host warhammer.iskarion.ddns.net;
            proxy_redirect off;
        }

    }
