services:
  #
  # ----------------------------------------------------------------------
  # WebMail
  # ----------------------------------------------------------------------
  #
  webmail-service:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - primary-network
      - mail-network
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.iskarion.ddns.net # Nombre del servicio de tu mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.iskarion.ddns.net
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_IMAP_CONN_OPTIONS='{"ssl":{"verify_peer":false,"verify_peer_name":false,"allow_self_signed":true}}'
      - ROUNDCUBEMAIL_SMTP_CONN_OPTIONS='{"ssl":{"verify_peer":false,"verify_peer_name":false,"allow_self_signed":true}}'
      - ROUNDCUBEMAIL_DSN=tls://mail-service:993?verify_peer=false&verify_peer_name=false&allow_self_signed=true
  #
  # ----------------------------------------------------------------------
  # Mail
  # ----------------------------------------------------------------------
  #
  mail-service:
    image: mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: iskarion.ddns.net
    ports:
      - "143:143"
      - "25:25"
      - "587:587"
    volumes:
      - /mail/data:/var/mail
      - /mail/state:/var/mail-state
      - /mail/config:/tmp/docker-mailserver
      - /cert/etc:/etc/letsencrypt
      - /cert/var:/var/lib/letsencrypt
      - /cert/webroot:/var/www/certbot
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/live/mail.iskarion.ddns.net/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/mail.iskarion.ddns.net/privkey.pem
    networks:
      - primary-network
      - mail-network
    restart: always
    extra_hosts:
      - "mail.iskarion.ddns.net:127.0.0.1"
  #
  # ----------------------------------------------------------------------
  # Database
  # ----------------------------------------------------------------------
  #
  postgres:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - sql-network
    volumes:
      # Postgres guarda sus datos en su ruta dedicada
      - /data/iskarion/postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh:ro
    restart: unless-stopped
  #
  # ----------------------------------------------------------------------
  # PGAdmin
  # ----------------------------------------------------------------------
  #
  pgadmin-service:
    image: dpage/pgadmin4
    container_name: database_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
      VIRTUAL_PORT: 8080
    networks:
      - primary-network
      - sql-network
    restart: unless-stopped
    depends_on:
      - postgres
  #
  # ----------------------------------------------------------------------
  # CertBot
  # ----------------------------------------------------------------------
  #
  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - primary-network
      - sql-network
    environment:
      CERTBOT_AUTORENEWAL: ${CERTBOT_AUTORENEWAL}
    volumes:
      - /cert/etc:/etc/letsencrypt
      - /cert/var:/var/lib/letsencrypt
      - /cert/webroot:/var/www/certbot
      - ./scripts/certbot-entrypoint.sh:/src/certbot-entrypoint.sh:ro
      - ./scripts/certbot-generate.sh:/src/certbot-generate.sh:ro
      - ./scripts/certbot-autorenewal.sh:/src/certbot-autorenewal.sh:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
  #
  # ----------------------------------------------------------------------
  # Proxy
  # ----------------------------------------------------------------------
  #
  nginx_proxy:
    image: nginx:latest
    container_name: proxy
    networks:
      - primary-network
      - mail-network
      - sql-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Montar proxy.conf para que encuentre los sites
      - /src/proxy/proxy.conf:/etc/nginx/proxy.conf
      - /src/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /src/proxy/error.conf:/etc/nginx/error.conf:ro
      # Custom Error Pages
      - /src/proxy/errors:/var/www/html/errors
      # Montar volumenes de certbot para que encuentre los certificados
      - /cert/etc:/etc/letsencrypt
      - /cert/var:/var/lib/letsencrypt
      - /cert/webroot:/var/www/certbot
      # Montar /static (monta todos los /static/XXXXX/ de cada django)
      - /static:/static
      # Montar /media/XXXXX/ de cada django
      - /src/cerebelus/web/media:/media/cerebelus
      - /src/sixdegrees/web/media:/media/sixdegrees
      - /src/adam/web/media:/media/adam
      - /src/cpanel/web/media:/media/cpanel
      - /src/melodify/web/media:/media/melodify
      - /src/m4gtracker/web/media:/media/m4gtracker
      - /src/scenia/web/media:/media/scenia
      - /src/warhammer/web/media:/media/warhammer
      - /src/byteworld/web/media:/media/byteworld
      - /src/trickynoid/back/media:/media/trickynoid
      - /src/trickynoid/back/static:/static/trickynoid
      # These are needed for each PHP project
      - /src/soundpanel/web:/var/www/html/soundpanel
      - /src/gallery/web:/var/www/html/gallery
      - /src/stuff/web:/var/www/html/stuff
      - /src/cells/web:/var/www/html/cells
      - /src/snake/web:/var/www/html/snake
      - /src/pacman/web:/var/www/html/pacman
      - /src/blackbox/server:/var/www/html/blackbox
      - /src/trickynoid/front:/var/www/html/trickynoid
      - /src/trickynoid/back:/src/trickynoid
    depends_on:
      - auth-service
      - pgadmin-service
  #
  # ----------------------------------------------------------------------
  # KeyCloak
  # ----------------------------------------------------------------------
  #
  auth-service:
    image: quay.io/keycloak/keycloak:24.0 # Versión optimizada y estable
    container_name: authentication
    command: start-dev # Usa 'start' con certificados SSL reales para producción
    environment:
      # Credenciales del Administrador de Keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      # Configuración de la Base de Datos
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # Características requeridas para producción / proxies inversos
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "true" # Cambiar a true si usas HTTPS/dominios reales
      KC_PROXY_HEADERS: xforwarded # Necesario si usas Nginx, Traefik o Apache delante
      KC_HOSTNAME: auth.iskarion.ddns.net  # <--- Tu dominio exacto de Keycloak
      KC_HOSTNAME_ADMIN: auth.iskarion.ddns.net # <--- Para poder entrar a la consola de admin
      KC_SPI_THEME_STATIC_MAX_AGE: -1
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
    volumes:
      - /src/proxy/themes:/opt/keycloak/themes
    networks:
      - primary-network
      - sql-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  primary-network:
    driver: bridge
  mail-network:
    driver: bridge
  sql-network:
    driver: bridge
