error_page 404 /errors/404.html;
location = /errors/404.html {
    root /var/www/html;
    internal;
}
error_page 404 /errors/403.html;
location = /errors/403.html {
    root /var/www/html;
    internal;
}
error_page 500 /errors/500.html;
location = /errors/500.html {
    root /var/www/html;
    internal;
}
error_page 502 /errors/502.html;
location = /errors/502.html {
    root /var/www/html;
    internal;
}
