events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    server {
        listen 80;


        error_page 404 /404.html;
        location = /404.html {
            root /var/www/html;
            internal;
        }
        error_page 502 /502.html;
        location = /502.html {
            root /var/www/html;
            internal;
        }

        # Bloquear User-Agents específicos conocidos (ej. escáneres, scrapers)
        if ($http_user_agent ~* (LWP::Simple|BBBike|wget|Baiduspider|MJ12bot|ClaudeBot|OAI-SearchBot|xAI-SearchBot|Google-CloudVertexBot|YandexBot|PerplexityBot|ChatGPT-User|GPTBot|CCBot|bingbot|Googlebot|DeepSeekBot)) {
            return 403;
        }

        # Ruta obligatoria para la validación de Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Envía todo el tráfico web al puerto seguro 443
        location / {
            return 301 https://$host$request_uri;
        }
    }
    include proxy.conf/*.conf;
}



