
# --------------------------------------------------------------------
# byteworld
# --------------------------------------------------------------------
server {
    listen 443 ssl;
    server_name byteworld.iskarion.ddns.net;
    ssl_certificate /etc/letsencrypt/live/byteworld.iskarion.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/byteworld.iskarion.ddns.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    include error.conf;

    location /static/ {
        alias /static/byteworld/;
    }

    location /media/ {
        alias /media/byteworld/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        proxy_pass http://byteworld-service:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host byteworld.iskarion.ddns.net;
        proxy_redirect off;
    }
}
