# gallery
server {
    listen 443 ssl;
    server_name gallery.iskarion.ddns.net;

    root /var/www/html/gallery;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/gallery.iskarion.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gallery.iskarion.ddns.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Procesar archivos PHP mediante el protocolo FastCGI
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Conexión al contenedor PHP-FPM
        fastcgi_pass gallery-service:9000;
    }
    # Enrutamiento para solicitudes principales
    location / {
        # Enviamos la petición hacia el index.php para que lo procese el bloque de arriba
        try_files $uri $uri/ /index.php?$query_string;
    }
}
