# --------------------------------------------------------------------
# tts
# --------------------------------------------------------------------
server {
    listen 443 ssl;
    server_name tts.iskarion.ddns.net;
    ssl_certificate /etc/letsencrypt/live/tts.iskarion.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tts.iskarion.ddns.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    location /static/ {
        alias /static/tts/;
    }
    location /media/ {
        alias /media/tts/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
    location / {
        proxy_pass http://tts-service:3000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host tts.iskarion.ddns.net;
        proxy_redirect off;
    }
}
